#%RAML 1.0 NamedExample

    [{
                "catagory_Id": 12345,
                "catagory_Name": "computer",
                "description": "this is the catagories of computer",
                
              },
              {
                "catagory_Id": 12345,
                "catagory_Name": "shoes",
                "description": "this is the catagories of shoes",
                 
              }]