#%RAML 1.0 NamedExample

     [{
                "orderId": 12345,
                "userId": 12567,
                "orderName": "Dell",
                "prodctId": 6789,
                "description": "cor I 7",
                "vidio_url": "www.dell.com",
                "price": 8000
              
              }]