#%RAML 1.0 NamedExample

 [{
                "productId": 1,
                "catagoryId": 13,
                "name": "HP",
                "description": "cor I 7",
                "vidio_url": "www.hp.com",
                "price": 7000
              },
              {
                 "productId": 2,
                "catagoryId": 13,
                "name": "Dell",
                "description": "cor I 7",
                "vidio_url": "www.dell.com",
                "price": 4000
              }]