#%RAML 1.0 NamedExample

  
    {
                "UserId": 12345,
                "UserName": "ephrem",
                "email": "yilimaepho@gmail.com"
                
              }
              