#%RAML 1.0 NamedExample
           [
             {
               orderId: 4545,
               userId: 8787,
               amount: 8000,
               discountId: 34,
               created: "01-01-2018 06:22:12",
               modified: "01-02-2018 07:40:43",
               adressId: 1234,
               status: "shipped"
              }
            ]
            