#%RAML 1.0 NamedExample
              {
                 productId: 1,
                 catagoryId: 13,
                 price: 4000,
                 description: "cor i 3",
                 name: "hp",
                 video: "www.dell.com"
              }