#%RAML 1.0 DataType
type: object
properties:
   
                orderId: integer
                userId: integer
                orderName: string
                prodctId: string
                description: string
                vidio_url: string
                price: string
                
         