#%RAML 1.0 Trait
responses:
  404:
    body:
      application/json:
        example:
          {
            "message": "resource not found"
          }
  500:
    body:
      application/json:
        example:
          {
            "message": "web acess faild"
          }
  403:
    body:
      application/json:
         example:
           {
             "message": "forbidden"
           }
  401:
    body:
      application/json:
        example:
          {
            "message": "unauthorized"
          }      