#%RAML 1.0 Extension
extends: craft-online-shoping.raml
usage: uses for admin task
/products:
  get:
  post:
  delete:
  /{product_id}:
    get:
    post:
    put:
    delete:
/user:
  get:
  post:
  delete:
  put:
/order:
  get:
  post:
  put:
  delete:
/catagories:
  get:
  post:
  delete:
  /{catagory}:
    get:
    post:
    put:
    delete:
      

   